title: GameLeaf
description: Your portal for indie and mobile games
url: "https://www.gameleaf.space"
baseurl: ""

author:
  name: Gryvery
  url: "https://www.gameleaf.space/about"

youtube_channel_id: UCo_22HGU2y0F06am8OjeXwg

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

theme: null

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/hero-bg.jpg